-- AlterTable
ALTER TABLE "GlobalSettings" ADD COLUMN IF NOT EXISTS "youthReferralBonus" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "GlobalSettings" ADD COLUMN IF NOT EXISTS "youthMaxAge" INTEGER NOT NULL DEFAULT 22;
